# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["SpadayTree"]


class SpadayTree(Component):
    """Pierre Trees file tree with serializable paths, selection, expansion, search, Git status, and per-path decorations."""

    tag = "spaday-tree"
    schema = ComponentSchema(
        tag="spaday-tree",
        class_name="SpadayTree",
        summary="Pierre Trees file tree with serializable paths, selection, expansion, search, Git status, and per-path decorations.",
        props=(
            PropertySchema(
                name="paths",
                kind="json",
                choices=(),
                default=None,
                description="Every file path the tree renders. Directories are inferred from '/' separators; a trailing slash names an explicit directory. Updating the list preserves current expansion.",
            ),
            PropertySchema(
                name="selected_paths",
                kind="json",
                choices=(),
                default=None,
                description="Selected paths, two-way via the selection-change event. Setting selected_paths expands ancestor directories to reveal the selection and scrolls the first selected path into view — a supported contract. A bare string is coerced to a one-element list.",
            ),
            PropertySchema(
                name="expanded_paths",
                kind="json",
                choices=(),
                default=None,
                description="Expanded directory paths (canonical 'dir/' form), two-way via the expansion-change event. Reading reflects the engine's current expansion; setting expands the listed directories and collapses all others, so list every directory that should stay open. A bare string is coerced to a one-element list. Independent of the selected_paths reveal.",
            ),
            PropertySchema(
                name="search",
                kind="string",
                choices=(),
                default=None,
                description="Search query filtering the tree; empty or null clears the search. Two-way via the search-change event.",
            ),
            PropertySchema(
                name="git_status",
                kind="json",
                choices=(),
                default=None,
                description="Git status entries [{path, status}] with status added | deleted | ignored | modified | renamed | untracked. Rendered as a preset over decorations: the engine's status letter and colors on the row, plus roll-up dots on ancestor directories. A decorations entry for the same path wins field-by-field.",
            ),
            PropertySchema(
                name="decorations",
                kind="json",
                choices=(),
                default=None,
                description="Per-path row decorations {path: {icon?, tone?, badge?, tooltip?}}. badge (short text) or icon (Pierre icon name or {name, width?, height?}) render after the label — badge wins when both are set; tooltip becomes the row title; tone adds a spaday-tone-<tone> class to the row. Built-in tones info | success | warning | danger | muted have light/dark colors overridable via --trees-tone-* custom properties.",
            ),
        ),
        events=("selection-change", "expansion-change", "search-change"),
        slots=(),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        paths: Any = None,
        selected_paths: Any = None,
        expanded_paths: Any = None,
        search: str | None = None,
        git_status: Any = None,
        decorations: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "paths": paths,
                "selected_paths": selected_paths,
                "expanded_paths": expanded_paths,
                "search": search,
                "git_status": git_status,
                "decorations": decorations,
            },
            **props,
        )
