# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any, Optional

from spaday.component import Child, Component

__all__ = ["SpadayTree"]


class SpadayTree(Component):
    """Pierre Trees file tree with serializable paths, selection, search, and Git status."""

    tag = "spaday-tree"

    def __init__(
        self,
        *children: Child,
        key: Optional[str] = None,  # noqa: UP045
        paths: Any = None,
        selected_paths: Any = None,
        search: Optional[str] = None,  # noqa: UP045
        git_status: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "paths": paths,
                "selected_paths": selected_paths,
                "search": search,
                "git_status": git_status,
            },
            **props,
        )
